// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: base_qm.proto

package gtest

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserQuotaReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Biz             string `protobuf:"bytes,2,opt,name=biz,proto3" json:"biz,omitempty"`
	Currency        string `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	UserId          string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PurchasedAmount string `protobuf:"bytes,5,opt,name=purchased_amount,json=purchasedAmount,proto3" json:"purchased_amount,omitempty"` //
}

func (x *GetUserQuotaReq) Reset() {
	*x = GetUserQuotaReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_qm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserQuotaReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserQuotaReq) ProtoMessage() {}

func (x *GetUserQuotaReq) ProtoReflect() protoreflect.Message {
	mi := &file_base_qm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserQuotaReq.ProtoReflect.Descriptor instead.
func (*GetUserQuotaReq) Descriptor() ([]byte, []int) {
	return file_base_qm_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserQuotaReq) GetBiz() string {
	if x != nil {
		return x.Biz
	}
	return ""
}

func (x *GetUserQuotaReq) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetUserQuotaReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserQuotaReq) GetPurchasedAmount() string {
	if x != nil {
		return x.PurchasedAmount
	}
	return ""
}

type GetQuotaTierResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BizType        string                            `protobuf:"bytes,5,opt,name=biz_type,json=bizType,proto3" json:"biz_type,omitempty"`
	Currency       string                            `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	ProductChannel int64                             `protobuf:"varint,7,opt,name=product_channel,json=productChannel,proto3" json:"product_channel,omitempty"`
	SubTypeIdList  []int64                           `protobuf:"varint,8,rep,packed,name=sub_type_id_list,json=subTypeIdList,proto3" json:"sub_type_id_list,omitempty"`
	TierQuotaList  []*GetQuotaTierResp_TierQuotaList `protobuf:"bytes,9,rep,name=tier_quota_list,json=tierQuotaList,proto3" json:"tier_quota_list,omitempty"`
}

func (x *GetQuotaTierResp) Reset() {
	*x = GetQuotaTierResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_qm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaTierResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaTierResp) ProtoMessage() {}

func (x *GetQuotaTierResp) ProtoReflect() protoreflect.Message {
	mi := &file_base_qm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaTierResp.ProtoReflect.Descriptor instead.
func (*GetQuotaTierResp) Descriptor() ([]byte, []int) {
	return file_base_qm_proto_rawDescGZIP(), []int{1}
}

func (x *GetQuotaTierResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetQuotaTierResp) GetBizType() string {
	if x != nil {
		return x.BizType
	}
	return ""
}

func (x *GetQuotaTierResp) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetQuotaTierResp) GetProductChannel() int64 {
	if x != nil {
		return x.ProductChannel
	}
	return 0
}

func (x *GetQuotaTierResp) GetSubTypeIdList() []int64 {
	if x != nil {
		return x.SubTypeIdList
	}
	return nil
}

func (x *GetQuotaTierResp) GetTierQuotaList() []*GetQuotaTierResp_TierQuotaList {
	if x != nil {
		return x.TierQuotaList
	}
	return nil
}

type GetQuotaTierResp_TierQuotaList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Max         string `protobuf:"bytes,1,opt,name=max,proto3" json:"max,omitempty"`
	Min         string `protobuf:"bytes,2,opt,name=min,proto3" json:"min,omitempty"`
	MatchAmount string `protobuf:"bytes,3,opt,name=match_amount,json=matchAmount,proto3" json:"match_amount,omitempty"`
	// 平均apy
	AvgApy string `protobuf:"bytes,4,opt,name=avg_apy,json=avgApy,proto3" json:"avg_apy,omitempty"`
	// apy 修改的数量
	ApyChange string `protobuf:"bytes,5,opt,name=apy_change,json=apyChange,proto3" json:"apy_change,omitempty"`
}

func (x *GetQuotaTierResp_TierQuotaList) Reset() {
	*x = GetQuotaTierResp_TierQuotaList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_base_qm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetQuotaTierResp_TierQuotaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQuotaTierResp_TierQuotaList) ProtoMessage() {}

func (x *GetQuotaTierResp_TierQuotaList) ProtoReflect() protoreflect.Message {
	mi := &file_base_qm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQuotaTierResp_TierQuotaList.ProtoReflect.Descriptor instead.
func (*GetQuotaTierResp_TierQuotaList) Descriptor() ([]byte, []int) {
	return file_base_qm_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetQuotaTierResp_TierQuotaList) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

func (x *GetQuotaTierResp_TierQuotaList) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *GetQuotaTierResp_TierQuotaList) GetMatchAmount() string {
	if x != nil {
		return x.MatchAmount
	}
	return ""
}

func (x *GetQuotaTierResp_TierQuotaList) GetAvgApy() string {
	if x != nil {
		return x.AvgApy
	}
	return ""
}

func (x *GetQuotaTierResp_TierQuotaList) GetApyChange() string {
	if x != nil {
		return x.ApyChange
	}
	return ""
}

var File_base_qm_proto protoreflect.FileDescriptor

var file_base_qm_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x71, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x67, 0x74, 0x65, 0x73, 0x74, 0x22, 0x83, 0x01, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x62, 0x69,
	0x7a, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x62, 0x69, 0x7a, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x5f, 0x61,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x70, 0x75, 0x72,
	0x63, 0x68, 0x61, 0x73, 0x65, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x8f, 0x03, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x54, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x7a, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x69, 0x7a, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x27, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x64,
	0x75, 0x63, 0x74, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x43, 0x68, 0x61, 0x6e, 0x6e, 0x65,
	0x6c, 0x12, 0x27, 0x0a, 0x10, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x08, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x75, 0x62,
	0x54, 0x79, 0x70, 0x65, 0x49, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x4f, 0x0a, 0x0f, 0x74, 0x69,
	0x65, 0x72, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x09, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x51,
	0x75, 0x6f, 0x74, 0x61, 0x54, 0x69, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x2e, 0x54, 0x69, 0x65,
	0x72, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x0d, 0x74, 0x69,
	0x65, 0x72, 0x51, 0x75, 0x6f, 0x74, 0x61, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x90, 0x01, 0x0a, 0x0f,
	0x54, 0x69, 0x65, 0x72, 0x5f, 0x71, 0x75, 0x6f, 0x74, 0x61, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61,
	0x78, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x69, 0x6e, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x61, 0x6d, 0x6f,
	0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6d, 0x61, 0x74, 0x63, 0x68,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x76, 0x67, 0x5f, 0x61, 0x70,
	0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x67, 0x41, 0x70, 0x79, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x70, 0x79, 0x5f, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x70, 0x79, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x67, 0x74, 0x65, 0x73, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_base_qm_proto_rawDescOnce sync.Once
	file_base_qm_proto_rawDescData = file_base_qm_proto_rawDesc
)

func file_base_qm_proto_rawDescGZIP() []byte {
	file_base_qm_proto_rawDescOnce.Do(func() {
		file_base_qm_proto_rawDescData = protoimpl.X.CompressGZIP(file_base_qm_proto_rawDescData)
	})
	return file_base_qm_proto_rawDescData
}

var file_base_qm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_base_qm_proto_goTypes = []interface{}{
	(*GetUserQuotaReq)(nil),                // 0: gtest.GetUserQuotaReq
	(*GetQuotaTierResp)(nil),               // 1: gtest.GetQuotaTierResp
	(*GetQuotaTierResp_TierQuotaList)(nil), // 2: gtest.GetQuotaTierResp.Tier_quota_list
}
var file_base_qm_proto_depIdxs = []int32{
	2, // 0: gtest.GetQuotaTierResp.tier_quota_list:type_name -> gtest.GetQuotaTierResp.Tier_quota_list
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_base_qm_proto_init() }
func file_base_qm_proto_init() {
	if File_base_qm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_base_qm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserQuotaReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_qm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaTierResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_base_qm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetQuotaTierResp_TierQuotaList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_base_qm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_base_qm_proto_goTypes,
		DependencyIndexes: file_base_qm_proto_depIdxs,
		MessageInfos:      file_base_qm_proto_msgTypes,
	}.Build()
	File_base_qm_proto = out.File
	file_base_qm_proto_rawDesc = nil
	file_base_qm_proto_goTypes = nil
	file_base_qm_proto_depIdxs = nil
}
